spring.application.name=spring-unit-project

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/link-garden}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Nf101308!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-http-form-post-size=200MB
server.tomcat.max-swallow-size=200MB
spring.servlet.multipart.enabled=true
