spring.application.name=spring-unit-project

spring.datasource.url=jdbc:postgresql://localhost:5432/quest-log
spring.datasource.username=postgres
spring.datasource.password=Nf101308!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-http-form-post-size=200MB
server.tomcat.max-swallow-size=200MB
spring.servlet.multipart.enabled=true